"""empty message

Revision ID: ddf186b3897a
Revises: 5330c1426b1b
Create Date: 2018-05-30 18:33:55.612668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf186b3897a'
down_revision = '5330c1426b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('note', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'blog', ['note'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='unique')
    op.drop_column('blog', 'note')
    # ### end Alembic commands ###
